### ISSUE TITLE
Network reaction to falsified ("forked") own feed?

### ISSUE THREAD

**Issue by ingokeck** [ssbc/ssb-db#157]
In the documentation I read that secure scuttlebutt sees the user feed as a blockchain, but I was not able to find any documentation about how the network actually decides the consensus about the state of this feed in case there are alternatives:

Imagine I as owner of the feed want to change a historic message with sequence number n_0. I could simply create a new message n_0 and re-create all later messages with their respective numbers and time stamps up to the last message n_f in the feed . I have the private key to do that so all messages validate correctly.  

How would the ssbc system react to that? In a blockchain, the network would either reject that attack in case of proof of work consensus if I did not invest at least the same amount of work as the chain already included in between messages n_0 and n_f. In case of a validation based blockchain the validators would simply refuse to sign my "falsified" out-of-sequence block (see https://medium.com/@ingokeck/introduction-what-is-a-blockchain-f22510332bff#.i75w5jz1x ). 

I see that something similar was discussed in issue #3 for the nodes that already have the feed, has that been implemented? What will happen if I send the new feed to many more pub nodes that did not have it before?

**Comment by dominictarr** [comment]
the current behavior is if the network has already received the original n_0 message, it would be expecting a n_1 message that points to that. If some nodes have not seen the original n_0 then they will accept the new one and your feed will be forked.

What I want, but hasn't been implemented yet, is when a fork is detected, that message is used to create a proof that the feed has forked, which can be given out when someone requests the feed, killing that feed.

Also, note that if Bob has any user interaction with a Alice's feed, such as a reply, like, etc, Bob does that by posting message which contains the hash the message by Alice, and also signing it as Bob - if you have lots of these, I think you could calculate a "social proof" based on that. This would give you something like a blockchain's ability to prove that a thing really did happen at a time, except it would be based on the assumption that not many keys in your (social) network are actually bots.

**Comment by GambolingPangolin** [comment]
Another possibility is to introduce a rule that nodes use to pick one branch through the hash tree.  The goal is to make it computationally expensive to create a fork that users will accept as valid.  For example, suppose a node observes a hash tree which is valid in the sense that all of the signatures verify.  Then we can choose a feed as follows:
```typescript
function feed(maximalPaths: Paths[]): Path {
  if (paths.length == 1) {
    return paths[0];
  else {
    let thePath = longestCommonPrefix(maximalPaths);
    for (path of paths) {
      // d = difficulty parameter
      // difficulty = difficulty function
      if (difficulty(path) > d && difficulty(path) > thePath) {
        thePath = path;
      }
    }
    return thePath;
  }
}
```
This scheme makes it cheap to create a single sequence of messages, but arbitrarily expensive to create vaild forks.  

If people like this idea, I would be happy to elaborate it into an implementation.

**Comment by GambolingPangolin** [comment]
There's yet another way to handle this.  Nodes can accept any DAG with a single tip (or terminal) message.  The canonical DAG for a given user-feed pair is then the one whose tip is the most recent common ancestor to all known tips.  The (probably fatal) problem with this is that it makes the feed hard to understand.

**Comment by dominictarr** [comment]
I don't like proof of work, but the graph analysis is really interesting. I don't understand the diagram you drew though. is each row a feed?

This could be very useful for filtering out sybils, and show that some message or feed is accepted by say X% of your network (because a reply signs the hash of the message replied to, you effectively sign both messages)

**Comment by GambolingPangolin** [comment]
Note that in the scheme that has a proof of work, the author does not need to produce a proof of work _unless_ she wants to create a fork.  The proof of work can be adjusted depending on the source of the feed as well, to control the degree of branching possible.  

The diagram is supposed to represent the hash graph of a single user's messages, when the user is allowed to include multiple previous messages as parents.  A little bit more formally, let `G = (V,E)` be a directed acyclic graph.  There is an associated partial order where for `v1, v2 in V` we say `v1 <= v2` if there is a path (possibly of length zero) in `G` starting at `v1` and ending at `v2`.  Given a set of vertices `{v1,...,vn}` we define their infimum under the partial order in the usual way.  Now if we encounter a user's hash graph, possibly very complicated, we compute the set of tips `{t1,...,tr}` and declare that our view of their graph is `{ v | v <= inf {t1, ..., tr } }`.  This means that some branching is allowed, but that users must merge branches together before the network will accept them.

I don't believe this addresses the problem with sybils.  My thinking here is in the model where each user is the single source of truth for their own data.  In order to encourage users to create nice totally ordered streams, we might make it very expensive to produce a non linear hash graph, or with might require that if they do create some forks that they eventually merge them again.

**Comment by AljoschaMeyer** [comment]
There are also replication considerations here. With a total order on feed items, Alice can start replication with Bob by simply sending the maximum item of her local copy of the feed. If Bob's local maximum is larger, he can send all items between these. Else, he can request all items larger than his maximum.

From a data validation perspective, we don't necessarily need a total order. But the total order enables the simple-yet-powerful replication that powers ssb.

**Comment by GambolingPangolin** [comment]
Yeah, for sure.  I think I need to learn more about the project before I can add anything intelligent.

**Comment by dominictarr** [comment]
Yeah, I have always pushed back strongly against forked replication because it would mean that round-trip complexity would become probably logarithmic, but with a total order per feed it's constant. round-trip complexity is much bigger killer if you have bad internet, which is the situation I want to optimize for.

(this is both my personal situation: I live on a boat in the antipodes, and where I believe the biggest opportunity for network growth is: the developing world, also there is a surprising number of infrastructure fails in the developed world too... your network provider may not have coverage here, etc)

**Comment by NilSet** [comment]
I think this is important to hammer out, since it will be a common failure mode for people attempting to use the same identity on multiple devices.

**Comment by jcalfee** [comment]
Probably better to separate out concerns.  If your talking about messages and replies they need only be signed and ordered by the timestamp in the message.  Trying to link them in a chain might be more than you need??  If a node sees a signed message timestamped in the future it can reject it.  This is a use case even if you get into token applications, think of a UN-verified check someone leaves to pay their bill because the payment network is not available.  It just gets included later, you don't know the prior block.  If you want to later put a strict order on it, the world knows this a creating a "block."

Forking unusually involves a re-org to loose forked blocks and the inclusion of those transactions in a new block.  The longest chain wins.  DPoS is my favorite, you know how many block creators you have and you know when they become irreversible.  Daniel Larimer and his team did a lot to create DPoS.  Dan is hinting at another radical upgrade in 2019..  This work may make your life easier. 

So the question is, can you make this more mesh friendly and not require a hash link for some use cases?  Kind of like a mem pool of transactions in Pubs and devices.  This way messages can just be included when they are discovered..  If you need a hash chain then make that something else that runs and collects up all the message types you need to include in order.

**Comment by christianbundy** [comment]
@jcalfee 

> So the question is, can you make this more mesh friendly and not require a hash link for some use cases?

Could you expand on this question? I think I'm a bit confused by the reference to transactions, blocks, mempools, etc., and I want to make sure I can accurately answer your question. I'd be especially interested in what you mean by "hash link" and whether that's `msg.key` or `msg.value.previous`.

**Comment by jcalfee** [comment]
I apologize, I'm still unfamiliar with ssb terms.  It is probably `msg.value.previous` .. If two offline devices produce a comment using the same secret key, they will both have the same previous value?  That causes a fork?  I'm wondering about a use case that would allow both messages to succeed or be resolved.  That is why I went into blocks where the transactions and the block are not attached to each other so, in that case, those two transactions would be valid and later ordered by a wrapping them in a block.

**Comment by christianbundy** [comment]
No problem! Thanks for taking the time to go a bit deeper.

> If two offline devices produce a comment using the same secret key, they will both have the same previous value? That causes a fork?

Yep, you got it. Feeds are meant to be linear, which means that each device should have its own feed so that we can avoid this problem. This makes gossip/replication simple because you can just reference each message by the sequence number (e.g. 42), because they're a list rather than a tree.

Instead of using the same private key on every device you use, the plan is to specify that feeds have a ["same as"](https://github.com/ssbc/ssb-same-as) relationship, which should make this more ergonomic and less awkward for multi-device users.

If you haven't already seen it, I'd highly recommend the [Scuttlebutt Protocol Guide](https://ssbc.github.io/scuttlebutt-protocol-guide/index.html), which may give you some more info on feeds and how they currently work.

**Comment by ingokeck** [comment]
I think right now that maybe the protocol guide is not really specific enough because it says 

> A Scuttlebutt feed is a list of all the messages posted by a particular identity

and that is not what seems to be intended by the protocol as far as I understand this discussion, instead a feed is a list of all messaged posted by a particular private key-holder on a particular device.

What I would like to understand is what would be the intended way of work from the point of view of the user. Do I as user expect one single chain of messages per user, or one per device, or one per private key? I actually see different applications for all. :-/ 
* E.g. replication of twitter service (one feed per reader = multiple feeds per sender and priv key) 
* subscribe to a sensor (one feed per device, maybe multiple devices per priv key)

Maybe this would be a usecase to adapt different solutions in the protocol?

**Comment by jcalfee** [comment]
Seems like for the twitter-like feed a library merge the `sameAs` feeds closer to the reader..  Even though it may be a little involved, the implementation could be shared (module) and have the benefit of testing different approaches.
